[package]
name = "rlinks-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
anyhow = "1.0"

[dev-dependencies]
tempfile = "3"
