[package]
name = "rlinks-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
url = "2"
thiserror = "1.0"
regex = "1"

[dev-dependencies]
serde_json = "1"
